receivers:
  jaeger:
    protocols:
      grpc:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: data-prepper:21890
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, otlp]
    metrics:
      receivers: [prometheus]
      exporters: [logging]