version: "3.9"

services:
  data-prepper:
    restart: unless-stopped
    image: ${DOCKER_IMAGE}
    working_dir: /usr/share/data-prepper/
    volumes:
      - ./data-prepper/config/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ./data-prepper/config/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ../../shared-config/log4j2.properties:/usr/share/data-prepper/config/log4j.properties
    depends_on:
      - opensearch
    ports:
      - "2021:2021"

  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    container_name: node-0.example.com
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  http-log-generation:
    restart: unless-stopped
    image: alpine
    volumes:
      - ./http-log-generation/entrypoint.sh:/entrypoint.sh
    command: /bin/sh -c 'set -x; apk --no-cache add curl && /bin/sh -f /entrypoint.sh'

  otel-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector:0.40.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./opentelemetry-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - data-prepper
    ports:
      - "4317:4317"

  otel-span-exporter:
    restart: unless-stopped
    build: ./otel-span-exporter
    depends_on:
      - otel-collector
