# Docs: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-api"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-core"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-expression"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-logstash-configuration"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-main"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-test-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/e2e-test"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/performance-test"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/release"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/aggregate-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/anomaly-detector-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/armeria-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/avro-codecs"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/aws-plugin"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/aws-plugin-api"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/aws-sqs-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/blocking-buffer"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/buffer-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/csv-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/date-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/dissect-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/drop-events-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/dynamodb-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/dynamodb-source-coordination-store"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/failures-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/grok-prepper"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/http-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/in-memory-source-coordination-store"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/kafka-connect-plugins"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/kafka-plugins"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/key-value-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/log-generator-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/mapdb-processor-state"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/mutate-event-processors"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/mutate-string-processors"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/newline-codecs"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/obfuscate-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/opensearch"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-logs-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-metrics-raw-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-metrics-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-proto-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-group-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-raw-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/parquet-codecs"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/parse-json-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/rss-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/s3-sink"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/s3-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/service-map-stateful"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/trace-peer-forwarder-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/translate-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/type-conversion-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/user-agent-processor"
  schedule:
    interval: monthly
