# Docs: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-api"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-core"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-expression"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-logstash-configuration"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/aggregate-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/armeria-common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/blocking-buffer"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/common"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/drop-events-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/grok-prepper"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/http-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/opensearch"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/mapdb-prepper-state"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-raw-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-raw-prepper"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-group-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-group-prepper"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-trace-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-metrics-raw-processor"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/otel-metrics-source"
  schedule:
    interval: monthly

- package-ecosystem: gradle
  directory: "/data-prepper-plugins/service-map-stateful"
  schedule:
    interval: monthly
