version: "3.7"
services:
  data-prepper:
    container_name: data-prepper
    build:
      args:
        DATA_PREPPER_VERSION: "2.0.0-SNAPSHOT"
      context: ../../..
      dockerfile: examples/dev/data-prepper-emf-monitoring/Dockerfile
    environment:
      AWS_EMF_AGENT_ENDPOINT: "tcp://fluent-bit:25888"
    volumes:
      - ./pipelines-raw-trace-stdout.yaml:/usr/share/data-prepper/pipelines/pipelines-raw-trace-stdout.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - "4900:4900" # DataPrepperServer port
      - "21890:21890" # OTelTraceSource port
    links:
      - fluent-bit
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "25888:25888"
