apiVersion: v1
data:
  data-prepper-config.yaml: |
    {{- toYaml .Values.dataPrepperConfig | nindent 6 }}
kind: ConfigMap
metadata:
  name: {{ include "data-prepper.configName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}

