routing-pipeline:
  workers: 4
  delay: 10
  source:
    in_memory:
      testing_key: ConditionalRoutingIT
  buffer:
    bounded_blocking:
      # Use a small batch size to help ensure that multiple threads
      # are picking up the different routes.
      batch_size: 10
  route:
    - alpha: '/value == "a"'
  sink:
    - in_memory:
        testing_key: ConditionalRoutingIT_alpha
        routes:
          - alpha
