minimal-pipeline:
  delay: 10
  workers: 4
  source:
    in_memory:
      testing_key: MultiWorkerPipelineIT

  buffer:
    bounded_blocking:
      buffer_size: 1000
      batch_size: 10

  processor:
    - thread_info:

  sink:
    - in_memory:
        testing_key: MultiWorkerPipelineIT