# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Data Prepper OpenSearchSink integration tests with Open Distro

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  integration_tests:
    strategy:
      matrix:
        java: [14]
        opendistro: [1.12.0, 1.13.2]

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Checkout Data-Prepper
        uses: actions/checkout@v2
      - name: Run Open Distro docker
        run: |
          docker pull amazon/opendistro-for-elasticsearch:${{ matrix.opendistro }}
          docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -d amazon/opendistro-for-elasticsearch:${{ matrix.opendistro }}
          sleep 90
      - name: Run Open Distro tests
        run: |
          ./gradlew :data-prepper-plugins:opensearch:test --tests "com.amazon.dataprepper.plugins.sink.opensearch.OpenSearchTests.testOpenSearchConnection" -Dos.host=https://localhost:9200 -Dos.user=admin -Dos.password=admin
          ./gradlew :data-prepper-plugins:opensearch:integTest --tests "com.amazon.dataprepper.plugins.sink.opensearch.OpenSearchSinkIT" -Dos=true -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=docker-cluster -Duser=admin -Dpassword=admin
