name: Build Release Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Checkout Data-Prepper
      uses: actions/checkout@v2
    - name: Build
      run: ./gradlew build
    - name: Archives
      run: ./gradlew :release:archives:linux:linuxTar -Prelease
    - name: Docker
      run: ./gradlew :release:docker:docker -Prelease
