name: Build Release Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Checkout Data-Prepper
      uses: actions/checkout@v2
    - name: Build Jar Files
      run: ./gradlew build
    - name: Build Archives
      run: ./gradlew :release:archives:buildArchives -Prelease
    - name: Build Docker Image
      run: ./gradlew :release:docker:docker -Prelease
    - name: Build Maven Artifacts
      run: ./gradlew publish
